# Kong API Gateway Helm Values
# Version: 2.20.1

# Core Kong configuration
kong:
  # High availability configuration with 3 base replicas
  replicaCount: 3

  image:
    repository: kong
    tag: "2.20.1-alpine"
    pullPolicy: IfNotPresent

  # Resource allocation for production workloads
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  # Horizontal Pod Autoscaling configuration
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # AWS NLB service annotations for cross-zone load balancing
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

  # Pod anti-affinity for high availability
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"

  # Node tolerations for dedicated API gateway nodes
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "api-gateway"
      effect: "NoSchedule"

# Kong plugin and security configuration
config:
  plugins:
    # JWT Authentication
    - name: jwt
      enabled: true
      config:
        header_names:
          - Authorization
        claims_to_verify:
          - exp
          - nbf
          - iss
        key_claim_name: kid
        secret_is_base64: true

    # Rate Limiting
    - name: rate-limiting
      enabled: true
      config:
        minute: 100
        hour: 5000
        policy: local
        fault_tolerant: true
        hide_client_headers: false

    # CORS Configuration
    - name: cors
      enabled: true
      config:
        origins:
          - "*"
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        headers:
          - Content-Type
          - Authorization
          - X-Request-ID
        exposed_headers:
          - X-Auth-Token
        credentials: true
        max_age: 3600
        preflight_continue: false

    # Prometheus Metrics
    - name: prometheus
      enabled: true
      config:
        status_code_metrics: true
        latency_metrics: true
        bandwidth_metrics: true
        upstream_health_metrics: true

    # IP Restriction
    - name: ip-restriction
      enabled: true
      config:
        allow:
          - "10.0.0.0/8"    # Private network ranges
          - "172.16.0.0/12"
          - "192.168.0.0/16"

# Monitoring configuration
monitoring:
  enabled: true
  
  # Prometheus ServiceMonitor configuration
  serviceMonitor:
    enabled: true
    interval: "30s"
    scrapeTimeout: "10s"
    namespace: monitoring
    labels:
      release: prometheus

  # PrometheusRule for alerts
  prometheusRule:
    enabled: true
    rules:
      # Alert on high latency
      - alert: KongHighLatency
        expr: kong_latency_bucket > 0.5
        for: 5m
        labels:
          severity: warning

      # Alert on high error rate
      - alert: KongHighErrorRate
        expr: sum(rate(kong_http_status{code=~"5.."}[5m])) / sum(rate(kong_http_status[5m])) > 0.05
        for: 5m
        labels:
          severity: critical