# Recording rules for Multi-Vertical Insurance Lead Generation Platform
# Evaluation interval: 1m
# Version: 1.0

groups:
  # Service-level HTTP metrics
  - name: service_metrics
    rules:
      # Error rate by service
      - record: job:http_requests_total:error_rate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (job) / sum(rate(http_requests_total[5m])) by (job)
        labels:
          metric_type: error_rate

      # 95th percentile latency by service
      - record: job:http_request_duration_seconds:p95
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (job, le))
        labels:
          metric_type: latency

  # Lead generation and processing metrics
  - name: lead_metrics
    rules:
      # Lead acceptance rate by vertical
      - record: vertical:leads_acceptance_rate:ratio
        expr: sum(rate(leads_accepted_total[30m])) by (vertical) / sum(rate(leads_submitted_total[30m])) by (vertical)
        labels:
          metric_type: acceptance_rate

      # 95th percentile lead processing time by vertical
      - record: vertical:lead_processing_duration:p95
        expr: histogram_quantile(0.95, sum(rate(lead_processing_duration_seconds_bucket[5m])) by (vertical, le))
        labels:
          metric_type: processing_time

  # Real-time bidding metrics
  - name: rtb_metrics
    rules:
      # RTB timeout rate by partner
      - record: rtb:bid_timeout_rate:ratio
        expr: sum(rate(rtb_bid_timeouts_total[5m])) by (partner) / sum(rate(rtb_bid_requests_total[5m])) by (partner)
        labels:
          metric_type: timeout_rate

      # 95th percentile RTB response time by partner
      - record: rtb:bid_response_time:p95
        expr: histogram_quantile(0.95, sum(rate(rtb_bid_duration_seconds_bucket[5m])) by (partner, le))
        labels:
          metric_type: latency

  # SLA and availability metrics
  - name: sla_metrics
    rules:
      # Service availability over 1 hour windows
      - record: service:availability:ratio
        expr: avg_over_time(up[1h])
        labels:
          metric_type: availability

      # Total concurrent users
      - record: service:concurrent_users:total
        expr: sum(rate(http_requests_total[5m]))
        labels:
          metric_type: capacity

  # Resource utilization metrics
  - name: resource_metrics
    rules:
      # Container CPU usage percentage
      - record: container:cpu_usage:percent
        expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) / sum(container_spec_cpu_quota) by (pod)
        labels:
          metric_type: resource_usage

      # Container memory usage percentage
      - record: container:memory_usage:percent
        expr: sum(container_memory_usage_bytes) by (pod) / sum(container_spec_memory_limit_bytes) by (pod)
        labels:
          metric_type: resource_usage