apiVersion: v1
kind: Service
metadata:
  name: campaign-service
  namespace: default
  labels:
    app: campaign-service
    tier: backend
    component: campaign-management
    environment: production
  annotations:
    # Prometheus metrics scraping configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
    # AWS Load Balancer configurations
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: campaign-service
  sessionAffinity: None
  publishNotReadyAddresses: false
  # Topology aware routing configuration
  topologyKeys:
    - "kubernetes.io/hostname"
  # Traffic policy configuration
  internalTrafficPolicy: Local
  # Connection draining configuration
  terminationGracePeriodSeconds: 60