apiVersion: v1
kind: Service
metadata:
  name: rtb-service
  namespace: default
  labels:
    app: rtb-service
    component: bidding
    part-of: insurance-platform
    tier: backend
    managed-by: kubernetes
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: ClusterIP
  ports:
    - name: http-api
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: prometheus-metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: rtb-service
    component: bidding
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800