version: '3.8'

services:
  # Jaeger Collector service - version 1.45.0
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.45.0
    ports:
      - "14250:14250"  # gRPC for receiving spans
      - "14268:14268"  # HTTP for receiving spans
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
      ES_USERNAME: elastic
      ES_INDEX_PREFIX: jaeger
      SAMPLING_STRATEGIES_FILE: /etc/jaeger/sampling.json
    volumes:
      - ./config:/etc/jaeger
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:14269/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Jaeger Query UI service - version 1.45.0
  jaeger-query:
    image: jaegertracing/jaeger-query:1.45.0
    ports:
      - "16686:16686"  # UI port
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
      ES_USERNAME: elastic
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:16687/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Jaeger Agent service - version 1.45.0
  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.45.0
    ports:
      - "5775:5775/udp"   # Zipkin compact thrift protocol
      - "6831:6831/udp"   # Jaeger thrift compact protocol
      - "6832:6832/udp"   # Jaeger thrift binary protocol
      - "5778:5778"       # Admin port: serve configs, sampling strategies
    environment:
      REPORTER_GRPC_HOST_PORT: jaeger-collector:14250
    depends_on:
      - jaeger-collector
    restart: unless-stopped
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5778/"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  config:
    driver: local

networks:
  monitoring:
    external: true

# Sampling configuration will be mounted at /etc/jaeger/sampling.json
configs:
  sampling:
    file: ./config/sampling.json
    template:
      default:
        type: probabilistic
        param: 1.0
      service_strategies:
        - service: lead-service
          type: probabilistic
          param: 1.0
        - service: rtb-service
          type: probabilistic
          param: 1.0

# Storage configuration for trace retention
x-storage-config: &storage-config
  retention:
    traces: 7d
    indices:
      prefix: jaeger-
      date_format: yyyy-MM-dd
      max_age: 7d